package code.enums;

public enum Attribute {
    INITIAL_PROSPERITY,
    INITIAL_FOOD,
    INITIAL_MATERIALS,
    INITIAL_ENERGY,
    UNIT_PRICE_FOOD,
    UNIT_PRICE_MATERIALS,
    UNIT_PRICE_ENERGY,
    AMOUNT_REQUEST_FOOD,
    DELAY_REQUEST_FOOD,
    AMOUNT_REQUEST_MATERIALS,
    DELAY_REQUEST_MATERIALS,
    AMOUNT_REQUEST_ENERGY,
    DELAY_REQUEST_ENERGY,
    PRICE_BUILD1,
    FOOD_USE_BUILD1,
    MATERIALS_USE_BUILD1,
    ENERGY_USE_BUILD1,
    PROSPERITY_BUILD1,
    PRICE_BUILD2,
    FOOD_USE_BUILD2,
    MATERIALS_USE_BUILD2,
    ENERGY_USE_BUILD2,
    PROSPERITY_BUILD2
}
